# Generated by Django 4.2.7 on 2023-12-02 06:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('32f11e56-5dbf-4d9a-a33e-891fea10aaff'), primary_key=True, serialize=False),
        ),
    ]
